import type { Metadata } from "next";
import "../../globals.css";
import SideNav from "./_components/side-nav";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row min-h-screen">
      <SideNav />
      {children}
    </div>
  );
}
