import { ReviewStatus } from "./_components/columns";

export const data: ReviewStatus[] = [
  {
    id: "1001",
    companyName: "팀A",
    ideaName: "스마트 농업 솔루션",
    field: "농업",
    status: "미심사",
    participantId: 100,
  },
  {
    id: "1002",
    companyName: "기업B",
    ideaName: "AI 의료 플랫폼",
    field: "의료",
    status: "미심사",
    participantId: 101,
  },
  {
    id: "1003",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1004",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1005",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1006",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1007",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1008",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1009",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1009",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1010",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1011",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1012",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
  {
    id: "1013",
    companyName: "팀C",
    ideaName: "친환경 에너지 기술",
    field: "에너지",
    status: "A(100)",
    participantId: 102,
  },
];
