

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_unique_evaluations"("judging_round" integer) RETURNS TABLE("judging_round_id" integer, "company_id" integer, "status" "text")
    LANGUAGE "sql"
    AS $$
  SELECT judging_round_id, company_id, status
  FROM evaluation
  WHERE judging_round_id = judging_round
  GROUP BY judging_round_id, company_id, status;
$$;


ALTER FUNCTION "public"."get_unique_evaluations"("judging_round" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."company" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."company" OWNER TO "postgres";


COMMENT ON TABLE "public"."company" IS '기업 테이블';



ALTER TABLE "public"."company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."evaluation" (
    "id" bigint NOT NULL,
    "judging_round_id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "evaluation_criterion_id" bigint NOT NULL,
    "grade" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text",
    "user_id" "uuid" NOT NULL,
    "feedback" "text"
);


ALTER TABLE "public"."evaluation" OWNER TO "postgres";


COMMENT ON TABLE "public"."evaluation" IS '평가를 저장하는 테이블';



COMMENT ON COLUMN "public"."evaluation"."grade" IS '점수(배점 만점)';



COMMENT ON COLUMN "public"."evaluation"."status" IS '심사 예정(PENDING) / 심사 중(ONGOING) / 심사 완료(DONE)';



COMMENT ON COLUMN "public"."evaluation"."feedback" IS '총평 및 피드백';



CREATE TABLE IF NOT EXISTS "public"."evaluation_criteria" (
    "id" bigint NOT NULL,
    "judging_round_id" bigint NOT NULL,
    "item_name" "text" NOT NULL,
    "points" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."evaluation_criteria" OWNER TO "postgres";


COMMENT ON TABLE "public"."evaluation_criteria" IS '각 심사 라운드의 평가 기준을 저장합니다.';



COMMENT ON COLUMN "public"."evaluation_criteria"."points" IS '배점';



COMMENT ON COLUMN "public"."evaluation_criteria"."description" IS '세부 평가 내용 상세';



ALTER TABLE "public"."evaluation_criteria" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluation_criteria_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."evaluation" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."judging_round" (
    "id" bigint NOT NULL,
    "program_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "start_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "end_date" "date"
);


ALTER TABLE "public"."judging_round" OWNER TO "postgres";


COMMENT ON TABLE "public"."judging_round" IS '프로그램 내의 각 심사 단계를 저장합니다.';



CREATE TABLE IF NOT EXISTS "public"."judging_round_company" (
    "id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "judging_round_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pdf_path" "text",
    "category" "text",
    "judge_num" integer,
    "feedback" "text",
    "group_name" "text"
);


ALTER TABLE "public"."judging_round_company" OWNER TO "postgres";


COMMENT ON TABLE "public"."judging_round_company" IS '각 심사 라운드에 참여하는 기업을 연결합니다.';



COMMENT ON COLUMN "public"."judging_round_company"."pdf_path" IS '발표자료 (pdf)가 저장된 경로';



COMMENT ON COLUMN "public"."judging_round_company"."category" IS 'program의 categories 중 하나';



COMMENT ON COLUMN "public"."judging_round_company"."judge_num" IS '접수 번호';



COMMENT ON COLUMN "public"."judging_round_company"."feedback" IS '총평 및 피드백';



COMMENT ON COLUMN "public"."judging_round_company"."group_name" IS '그룹 이름';



ALTER TABLE "public"."judging_round_company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."judging_round_company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."judging_round" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."judging_round_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."judging_round_user" (
    "id" bigint NOT NULL,
    "judging_round_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "group_name" "text"
);


ALTER TABLE "public"."judging_round_user" OWNER TO "postgres";


COMMENT ON TABLE "public"."judging_round_user" IS '각 심사 라운드에 배정된 심사자를 연결합니다.';



COMMENT ON COLUMN "public"."judging_round_user"."group_name" IS '할당된 그룹';



ALTER TABLE "public"."judging_round_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."judging_round_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."program" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "start_date" "date",
    "end_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "categories" "text"[]
);


ALTER TABLE "public"."program" OWNER TO "postgres";


COMMENT ON COLUMN "public"."program"."categories" IS '지원 분야(리스트)';



CREATE TABLE IF NOT EXISTS "public"."program_company" (
    "id" bigint NOT NULL,
    "program_id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."program_company" OWNER TO "postgres";


COMMENT ON TABLE "public"."program_company" IS '프로그램에 참여하는 기업을 연결하는 테이블';



ALTER TABLE "public"."program_company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."program_company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."program" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."program_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user" (
    "username" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "email" "text",
    "role" "text" DEFAULT '심사자'::"text" NOT NULL,
    "affiliation" "text",
    "position" "text",
    "phone_number" "text",
    "id" "uuid" NOT NULL,
    CONSTRAINT "user_role_check" CHECK (("role" = ANY (ARRAY['관리자'::"text", '심사자'::"text"])))
);


ALTER TABLE "public"."user" OWNER TO "postgres";


COMMENT ON TABLE "public"."user" IS '유저 정보';



COMMENT ON COLUMN "public"."user"."role" IS '"심자자", "관리자" 등 역할을 설정하는 컬럼';



COMMENT ON COLUMN "public"."user"."affiliation" IS '소속';



COMMENT ON COLUMN "public"."user"."position" IS '직위(ex. CEO, CTO...)';



COMMENT ON COLUMN "public"."user"."phone_number" IS '핸드폰 번호';



ALTER TABLE ONLY "public"."company"
    ADD CONSTRAINT "company_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."company"
    ADD CONSTRAINT "company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluation_criteria"
    ADD CONSTRAINT "evaluation_criteria_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_unique_constraint" UNIQUE ("judging_round_id", "company_id", "user_id", "evaluation_criterion_id");



ALTER TABLE ONLY "public"."judging_round_company"
    ADD CONSTRAINT "judging_round_company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."judging_round"
    ADD CONSTRAINT "judging_round_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."judging_round_user"
    ADD CONSTRAINT "judging_round_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."program_company"
    ADD CONSTRAINT "program_company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."program"
    ADD CONSTRAINT "program_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."program"
    ADD CONSTRAINT "program_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_name_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."evaluation_criteria"
    ADD CONSTRAINT "evaluation_criteria_judging_round_id_fkey" FOREIGN KEY ("judging_round_id") REFERENCES "public"."judging_round"("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_evaluation_criterion_id_fkey" FOREIGN KEY ("evaluation_criterion_id") REFERENCES "public"."evaluation_criteria"("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_judging_round_id_fkey" FOREIGN KEY ("judging_round_id") REFERENCES "public"."judging_round"("id");



ALTER TABLE ONLY "public"."evaluation"
    ADD CONSTRAINT "evaluation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id");



ALTER TABLE ONLY "public"."judging_round_company"
    ADD CONSTRAINT "judging_round_company_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."judging_round_company"
    ADD CONSTRAINT "judging_round_company_judging_round_id_fkey" FOREIGN KEY ("judging_round_id") REFERENCES "public"."judging_round"("id");



ALTER TABLE ONLY "public"."judging_round"
    ADD CONSTRAINT "judging_round_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "public"."program"("id");



ALTER TABLE ONLY "public"."judging_round_user"
    ADD CONSTRAINT "judging_round_user_judging_round_id_fkey" FOREIGN KEY ("judging_round_id") REFERENCES "public"."judging_round"("id");



ALTER TABLE ONLY "public"."judging_round_user"
    ADD CONSTRAINT "judging_round_user_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id");



ALTER TABLE ONLY "public"."program_company"
    ADD CONSTRAINT "program_company_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."program_company"
    ADD CONSTRAINT "program_company_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "public"."program"("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_unique_evaluations"("judging_round" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_unique_evaluations"("judging_round" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_unique_evaluations"("judging_round" integer) TO "service_role";


















GRANT ALL ON TABLE "public"."company" TO "anon";
GRANT ALL ON TABLE "public"."company" TO "authenticated";
GRANT ALL ON TABLE "public"."company" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."evaluation" TO "anon";
GRANT ALL ON TABLE "public"."evaluation" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluation" TO "service_role";



GRANT ALL ON TABLE "public"."evaluation_criteria" TO "anon";
GRANT ALL ON TABLE "public"."evaluation_criteria" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluation_criteria" TO "service_role";



GRANT ALL ON SEQUENCE "public"."evaluation_criteria_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluation_criteria_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluation_criteria_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."evaluation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."judging_round" TO "anon";
GRANT ALL ON TABLE "public"."judging_round" TO "authenticated";
GRANT ALL ON TABLE "public"."judging_round" TO "service_role";



GRANT ALL ON TABLE "public"."judging_round_company" TO "anon";
GRANT ALL ON TABLE "public"."judging_round_company" TO "authenticated";
GRANT ALL ON TABLE "public"."judging_round_company" TO "service_role";



GRANT ALL ON SEQUENCE "public"."judging_round_company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."judging_round_company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."judging_round_company_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."judging_round_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."judging_round_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."judging_round_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."judging_round_user" TO "anon";
GRANT ALL ON TABLE "public"."judging_round_user" TO "authenticated";
GRANT ALL ON TABLE "public"."judging_round_user" TO "service_role";



GRANT ALL ON SEQUENCE "public"."judging_round_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."judging_round_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."judging_round_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."program" TO "anon";
GRANT ALL ON TABLE "public"."program" TO "authenticated";
GRANT ALL ON TABLE "public"."program" TO "service_role";



GRANT ALL ON TABLE "public"."program_company" TO "anon";
GRANT ALL ON TABLE "public"."program_company" TO "authenticated";
GRANT ALL ON TABLE "public"."program_company" TO "service_role";



GRANT ALL ON SEQUENCE "public"."program_company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."program_company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."program_company_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."program_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user" TO "anon";
GRANT ALL ON TABLE "public"."user" TO "authenticated";
GRANT ALL ON TABLE "public"."user" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
